Traceback (most recent call last):
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pt1.loc[:, "ime"] == pt1.loc[:, ["ime"]]
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/var/folders/g7/xgt9ckmj6g1404knwg8j5rkc0000gn/T/ipykernel_6780/4100154151.py[0m in [0;36m?[0;34m()[0m
[0;32m----> 1[0;31m [0mpt1[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;34m"ime"[0m[0;34m][0m [0;34m==[0m [0mpt1[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;34m[[0m[0;34m"ime"[0m[0;34m][0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/predmeti/pandas/venv/lib/python3.11/site-packages/pandas/core/ops/common.py[0m in [0;36m?[0;34m(self, other)[0m
[1;32m     72[0m                     [0;32mreturn[0m [0mNotImplemented[0m[0;34m[0m[0;34m[0m[0m
[1;32m     73[0m [0;34m[0m[0m
[1;32m     74[0m         [0mother[0m [0;34m=[0m [0mitem_from_zerodim[0m[0;34m([0m[0mother[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     75[0m [0;34m[0m[0m
[0;32m---> 76[0;31m         [0;32mreturn[0m [0mmethod[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mother[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/predmeti/pandas/venv/lib/python3.11/site-packages/pandas/core/arraylike.py[0m in [0;36m?[0;34m(self, other)[0m
[1;32m     38[0m     [0;34m@[0m[0munpack_zerodim_and_defer[0m[0;34m([0m[0;34m"__eq__"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     39[0m     [0;32mdef[0m [0m__eq__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mother[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 40[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_cmp_method[0m[0;34m([0m[0mother[0m[0;34m,[0m [0moperator[0m[0;34m.[0m[0meq[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/predmeti/pandas/venv/lib/python3.11/site-packages/pandas/core/frame.py[0m in [0;36m?[0;34m(self, other, op)[0m
[1;32m   7628[0m     [0;32mdef[0m [0m_cmp_method[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mother[0m[0;34m,[0m [0mop[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7629[0m         [0maxis[0m[0;34m:[0m [0mLiteral[0m[0;34m[[0m[0;36m1[0m[0;34m][0m [0;34m=[0m [0;36m1[0m  [0;31m# only relevant for Series other case[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7630[0m [0;34m[0m[0m
[0;32m-> 7631[0;31m         [0mself[0m[0;34m,[0m [0mother[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_align_for_op[0m[0;34m([0m[0mother[0m[0;34m,[0m [0maxis[0m[0;34m,[0m [0mflex[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m [0mlevel[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   7632[0m [0;34m[0m[0m
[1;32m   7633[0m         [0;31m# See GH#4537 for discussion of scalar op behavior[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7634[0m         [0mnew_data[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_dispatch_frame_op[0m[0;34m([0m[0mother[0m[0;34m,[0m [0mop[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/predmeti/pandas/venv/lib/python3.11/site-packages/pandas/core/frame.py[0m in [0;36m?[0;34m(self, other, axis, flex, level)[0m
[1;32m   7935[0m             [0;31m# axis=1 is default for DataFrame-with-Series op[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7936[0m             [0maxis[0m [0;34m=[0m [0maxis[0m [0;32mif[0m [0maxis[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m [0;32melse[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7937[0m             [0;32mif[0m [0;32mnot[0m [0mflex[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7938[0m                 [0;32mif[0m [0;32mnot[0m [0mleft[0m[0;34m.[0m[0maxes[0m[0;34m[[0m[0maxis[0m[0;34m][0m[0;34m.[0m[0mequals[0m[0;34m([0m[0mright[0m[0;34m.[0m[0mindex[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 7939[0;31m                     raise ValueError(
[0m[1;32m   7940[0m                         [0;34m"Operands are not aligned. Do "[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7941[0m                         [0;34m"`left, right = left.align(right, axis=1, copy=False)` "[0m[0;34m[0m[0;34m[0m[0m
[1;32m   7942[0m                         [0;34m"before operating."[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: Operands are not aligned. Do `left, right = left.align(right, axis=1, copy=False)` before operating.

