Traceback (most recent call last):
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ljupco/predmeti/pandas/venv/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ocene_ana = studenti_ocene.loc[studenti_ocene.ime == "Ana", :]

(
    p9.ggplot(ocene_ana) +
    p9.aes(
        x = None,
        y = "rezultat",
        color = "semester_kolokvij",
        fill = "semester_kolokvij"
    ) +
    p9.geom_col() +
    p9.ylim(0, 400) +
    p9.coord_polar(theta = "y", start = 0)
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[30], line 13[0m
[1;32m      1[0m ocene_ana [38;5;241m=[39m studenti_ocene[38;5;241m.[39mloc[studenti_ocene[38;5;241m.[39mime [38;5;241m==[39m [38;5;124m"[39m[38;5;124mAna[39m[38;5;124m"[39m, :]
[1;32m      3[0m (
[1;32m      4[0m     p9[38;5;241m.[39mggplot(ocene_ana) [38;5;241m+[39m
[1;32m      5[0m     p9[38;5;241m.[39maes(
[1;32m      6[0m         x [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m      7[0m         y [38;5;241m=[39m [38;5;124m"[39m[38;5;124mrezultat[39m[38;5;124m"[39m,
[1;32m      8[0m         color [38;5;241m=[39m [38;5;124m"[39m[38;5;124msemester_kolokvij[39m[38;5;124m"[39m,
[1;32m      9[0m         fill [38;5;241m=[39m [38;5;124m"[39m[38;5;124msemester_kolokvij[39m[38;5;124m"[39m
[1;32m     10[0m     ) [38;5;241m+[39m
[1;32m     11[0m     p9[38;5;241m.[39mgeom_col() [38;5;241m+[39m
[1;32m     12[0m     p9[38;5;241m.[39mylim([38;5;241m0[39m, [38;5;241m400[39m) [38;5;241m+[39m
[0;32m---> 13[0m     [43mp9[49m[38;5;241;43m.[39;49m[43mcoord_polar[49m(theta [38;5;241m=[39m [38;5;124m"[39m[38;5;124my[39m[38;5;124m"[39m, start [38;5;241m=[39m [38;5;241m0[39m)
[1;32m     14[0m )

[0;31mAttributeError[0m: module 'plotnine' has no attribute 'coord_polar'

